security:
    encoders:
        Notejam\UserBundle\Entity\User:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10
 
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
 
    providers:
        user_db:
            entity: { class: Notejam\UserBundle\Entity\User, property: email }
 
    firewalls:
        main:
            pattern: /.*
            provider: user_db
            form_login:
                login_path: /signin
                check_path: /login_check
                username_parameter: form[email]
                password_parameter: form[password]
                default_target_path: /settings
                remember_me: true
            logout:
                path: /signout
                target: /
            remember_me:
                key: MiPassphrase
                lifetime: 1800
                path: /.*
                domain: ~
            security: true
            anonymous: true
    access_control:
        - { path: /settings, roles: ROLE_USER }
        - { path: /, roles: IS_AUTHENTICATED_ANONYMOUSLY }
