homepage:
    pattern:  /hello/{name}
    defaults: { _controller: NotejamUserBundle:User:index }

signup:
    pattern:  /signup
    defaults: { _controller: NotejamUserBundle:User:signup }

signin:
    pattern: /signin
    defaults: { _controller: NotejamUserBundle:User:signin }

settings:
    pattern:  /settings
    defaults: { _controller: NotejamUserBundle:User:settings }

login_check:
    pattern: /login_check
 
logout:
    pattern: /logout
