parameters:
#    notejam_user.example.class: Notejam\UserBundle\Example

services:
#    notejam_user.example:
#        class: %notejam_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
