homepage:
    pattern:  /
    defaults: { _controller: NotejamNoteBundle:Note:index }

create_pad:
    pattern:  /pads/create
    defaults: { _controller: NotejamNoteBundle:Pad:create }

edit_pad:
    pattern:  /pads/{id}/edit
    defaults: { _controller: NotejamNoteBundle:Pad:edit }
