parameters:
#    notejam_note.example.class: Notejam\NoteBundle\Example

services:
#    notejam_note.example:
#        class: %notejam_note.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
